services :
  db :
   image : postgres:latest
   container_name: my_db_compose
   ports:
    - "55432:5432"
   environment:
    - POSTGRES_DB=pleum 
    - POSTGRES_USER=pleum
    - POSTGRES_PASSWORD=pleum
  app:
    image: prawee/strapi:latest
    container_name: my_app_compose
    ports:
    - "8080:1337"
    environment:
        DATABASE_HOST: 192.168.1.143
        DATABASE_PORT: 55432
        DATABASE_NAME: pleum 
        DATABASE_USERNAME: pleum 
        DATABASE_PASSWORD: pleum 